Fix dtype mismatch in `_nodes_by_counts()` on 32-bit arch (#2321)
When running `skbio.diversity._phylogenetic._nodes_by_counts()` on 32-bit architecture (e.g. Pyodide/WebAssembly), an error is raised due to dtype mismatch between 32-bit and 64-bit pointers:

```
ValueError: Buffer dtype mismatch, expected 'intp_t' but got 'long long'
```

Changing the dtype from `np.int64` to `np.intp` fixes the error.